### GET request to example server
GET http://localhost:8080/users/all
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJodHRwOi8vbG9jYWxob3N0OjgwODAiLCJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjgwODAiLCJpZCI6MSwicm9sZSI6IlVTRVIiLCJleHAiOjE3NTAyMjM3Mzl9.Mjmq-kMx3bPKfvYWV1HmHvziqOh_6iCXoa5ESjIa_i4"
}

###


###
POST http://localhost:8080/auth/signup
Content-Type: application/json

{
  "username": "Demo",
  "email": "amansaeini204a@gmail.com",
  "password": "2312",
  "mobile": "0987e6254321",
  "firstName": "Aman",
  "lastName": "Saini",
  "bio": "HELLO"
}

###


###
POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "email": "amansaini04a@gmail.com",
  "password": "2312"
}

###