### GET request to example server
GET http://localhost:8080/users/all
Content-Type: application/json


###


###
POST http://localhost:8080/auth/signup
Content-Type: application/json

{
  "username": "Demo",
  "email": "amansaeini204a@gmail.com",
  "password": "2312",
  "mobile": "0987e6254321",
  "firstName": "Aman",
  "lastName": "Saini",
  "bio": "HELLO"
}

###


###
POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "email": "amansaini04a@gmail.com",
  "password": "2312"
}

###